# Generated by Django 4.2.6 on 2023-11-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Расходы', 'verbose_name_plural': 'Расходы'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'Кошельки', 'verbose_name_plural': 'Кошельки'},
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='wallet_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='wallet',
        ),
    ]
