# Generated by Django 4.2.6 on 2023-11-25 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_wallet_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Расход')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.category')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.wallet')),
            ],
            options={
                'verbose_name': 'Доходы',
                'verbose_name_plural': 'Доходы',
            },
        ),
    ]
